#port: 10900
#
#project:
#  name: pitaya
#
#
#server:
#  port: 8080
#
#spring:
#  application:
#    name: pitaya
#  datasource:  # 数据源配置
#    url: jdbc:mysql://localhost:3306/pitaya  #数据库名暂时为test
#    username: root
#    password: 123456qin
#
