spring:
# mysql
  datasource:
    url: jdbc:mysql://localhost:3306/pitaya?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456qin
# redis
  data:
    redis:
      password: 01star
      sentinel:
        master: mymaster
        nodes:
          - 192.168.131.128:27001
          - 192.168.131.128:27002
          - 192.168.131.128:27003
# rabbitmq
  rabbitmq:
    host: 192.168.131.128
    port: 5672
    username: admin
    password: 123456qin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
# 邮箱服务
  mail:
    host: smtp.qq.com
    port: 587
    username: 3436134614@qq.com
    password: ${OWL_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp



# 本项目启动端口
server:
  port: 8080
