INSERT INTO feature (icon, title, description, sort_order)
VALUES ('fa-solid fa-microchip',
        '新一代自研芯片',
        '采用 4nm 先进制程，集成超过 200 亿个晶体管，CPU 性能提升 150%，能效比提升 200%，为极致体验提供澎湃动力。',
        1),
       ('fa-solid fa-bolt',
        '闪充技术',
        '支持 120W 有线超级闪充，10 分钟充至 50%，25 分钟完全充满。同时支持 50W 无线闪充，随时随刻满电出发。',
        2),
       ('fa-solid fa-shield-halved',
        '金融级安全防护',
        '内置独立安全芯片，通过了多项国际安全认证。支持人脸识别、指纹解锁等多重生物识别技术，全方位守护您的隐私。',
        3),
       ('fa-solid fa-cloud-arrow-up',
        '无缝云同步',
        '跨设备无缝同步数据，手机、平板、电脑实时协作。支持 5TB 超大云空间，重要文件云端备份，随时随地访问。',
        4),
       ('fa-solid fa-palette',
        '专业级影像系统',
        '联合光学巨头打造，支持 8K 视频录制。AI 计算摄影让每个人都能拍出大师级作品，暗光拍摄噪点降低 80%。',
        5),
       ('fa-solid fa-headphones',
        '沉浸式空间音频',
        '搭载自研空间音频引擎，支持头部追踪。无论是音乐还是电影，都能获得身临其境的三维听觉体验。',
        6);


INSERT INTO spotlight (eyebrow, title, description, imageUrl, `order`, link, target)
VALUES ('全新发布',
        '2026 旗舰新品震撼上市',
        '搭载新一代自研芯片，性能提升 200%，续航突破 36 小时，重新定义智能体验。',
        '/images/banner/flagship-2026.jpg',
        1,
        '/products/flagship-2026',
        '_self'),
       ('限时优惠',
        '年终大促 · 全场低至 5 折',
        '精选爆款产品限时特惠，叠加优惠券更划算，活动截止至 12 月 31 日。',
        '/images/banner/year-end-sale.jpg',
        2,
        '/promotions/year-end-sale',
        '_self'),
       ('技术突破',
        '自研 AI 大模型全面开放',
        '全新一代 AI 助手正式上线，支持多模态交互、实时翻译、智能创作，免费体验。',
        '/images/banner/ai-model.jpg',
        3,
        'https://ai-demo.example.com',
        '_blank'),
       ('生态新品',
        '智能穿戴设备全家桶',
        '手表 + 耳机 + 戒指，无缝互联，健康数据一站式管理，套装购买立减 500。',
        '/images/banner/wearable-family.jpg',
        4,
        '/products/wearable-bundle',
        '_self'),
       ('开发者大会',
        '2026 开发者大会开放报名',
        '北京 · 国家会议中心，6 月 15-16 日，与大咖面对面交流前沿技术，早鸟票开抢中。',
        '/images/banner/dev-conf-2026.jpg',
        5,
        'https://devconf.example.com/register',
        '_blank');