package xyz.nanian.owl.pitaya.mapper;

import xyz.nanian.owl.pitaya.entity.OrderDetail;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..order_detail
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..order_detail
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insert(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..order_detail
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insertSelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..order_detail
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    OrderDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..order_detail
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKeySelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..order_detail
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKey(OrderDetail row);
}