package xyz.nanian.owl.pitaya.mapper;

import xyz.nanian.owl.pitaya.entity.Orders;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..orders
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..orders
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insert(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..orders
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insertSelective(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..orders
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    Orders selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..orders
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKeySelective(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..orders
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKey(Orders row);
}