package xyz.nanian.owl.pitaya.mapper;

import xyz.nanian.owl.pitaya.entity.ProductCategory;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..product_category
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..product_category
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insert(ProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..product_category
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insertSelective(ProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..product_category
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    ProductCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..product_category
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKeySelective(ProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..product_category
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKey(ProductCategory row);
}