package xyz.nanian.owl.pitaya.mapper;

import xyz.nanian.owl.pitaya.entity.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insert(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insertSelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKeySelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKey(Role row);
}