package xyz.nanian.owl.pitaya.mapper;

import xyz.nanian.owl.pitaya.entity.StatsDaily;

public interface StatsDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..stats_daily
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..stats_daily
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insert(StatsDaily row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..stats_daily
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insertSelective(StatsDaily row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..stats_daily
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    StatsDaily selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..stats_daily
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKeySelective(StatsDaily row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..stats_daily
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKey(StatsDaily row);
}