package xyz.nanian.owl.pitaya.mapper;

import xyz.nanian.owl.pitaya.entity.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..user_role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..user_role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insert(UserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..user_role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int insertSelective(UserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..user_role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..user_role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKeySelective(UserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitaya..user_role
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    int updateByPrimaryKey(UserRole row);
}