package xyz.nanian.owl.pitaya.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.order_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.user_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.status
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.total_amount
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.order_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.ship_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date shipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..orders.finish_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date finishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.id
     *
     * @return the value of pitaya..orders.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.id
     *
     * @param id the value for pitaya..orders.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.order_code
     *
     * @return the value of pitaya..orders.order_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.order_code
     *
     * @param orderCode the value for pitaya..orders.order_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.user_id
     *
     * @return the value of pitaya..orders.user_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.user_id
     *
     * @param userId the value for pitaya..orders.user_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.status
     *
     * @return the value of pitaya..orders.status
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.status
     *
     * @param status the value for pitaya..orders.status
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.total_amount
     *
     * @return the value of pitaya..orders.total_amount
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.total_amount
     *
     * @param totalAmount the value for pitaya..orders.total_amount
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.order_time
     *
     * @return the value of pitaya..orders.order_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.order_time
     *
     * @param orderTime the value for pitaya..orders.order_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.ship_time
     *
     * @return the value of pitaya..orders.ship_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.ship_time
     *
     * @param shipTime the value for pitaya..orders.ship_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setShipTime(Date shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..orders.finish_time
     *
     * @return the value of pitaya..orders.finish_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..orders.finish_time
     *
     * @param finishTime the value for pitaya..orders.finish_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
}