package xyz.nanian.owl.pitaya.entity;

import java.math.BigDecimal;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.detail_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String detailCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.order_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.product_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.product_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.quantity
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.unit_price
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.total_price
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..order_detail.remark
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.id
     *
     * @return the value of pitaya..order_detail.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.id
     *
     * @param id the value for pitaya..order_detail.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.detail_code
     *
     * @return the value of pitaya..order_detail.detail_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getDetailCode() {
        return detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.detail_code
     *
     * @param detailCode the value for pitaya..order_detail.detail_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setDetailCode(String detailCode) {
        this.detailCode = detailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.order_id
     *
     * @return the value of pitaya..order_detail.order_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.order_id
     *
     * @param orderId the value for pitaya..order_detail.order_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.product_id
     *
     * @return the value of pitaya..order_detail.product_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.product_id
     *
     * @param productId the value for pitaya..order_detail.product_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.product_name
     *
     * @return the value of pitaya..order_detail.product_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.product_name
     *
     * @param productName the value for pitaya..order_detail.product_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.quantity
     *
     * @return the value of pitaya..order_detail.quantity
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.quantity
     *
     * @param quantity the value for pitaya..order_detail.quantity
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.unit_price
     *
     * @return the value of pitaya..order_detail.unit_price
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.unit_price
     *
     * @param unitPrice the value for pitaya..order_detail.unit_price
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.total_price
     *
     * @return the value of pitaya..order_detail.total_price
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.total_price
     *
     * @param totalPrice the value for pitaya..order_detail.total_price
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..order_detail.remark
     *
     * @return the value of pitaya..order_detail.remark
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..order_detail.remark
     *
     * @param remark the value for pitaya..order_detail.remark
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}