package xyz.nanian.owl.pitaya.entity;

import java.util.Date;

public class ProductCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..product_category.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..product_category.category_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String categoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..product_category.category_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..product_category.description
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..product_category.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..product_category.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..product_category.update_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..product_category.id
     *
     * @return the value of pitaya..product_category.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..product_category.id
     *
     * @param id the value for pitaya..product_category.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..product_category.category_code
     *
     * @return the value of pitaya..product_category.category_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..product_category.category_code
     *
     * @param categoryCode the value for pitaya..product_category.category_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..product_category.category_name
     *
     * @return the value of pitaya..product_category.category_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..product_category.category_name
     *
     * @param categoryName the value for pitaya..product_category.category_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..product_category.description
     *
     * @return the value of pitaya..product_category.description
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..product_category.description
     *
     * @param description the value for pitaya..product_category.description
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..product_category.enabled
     *
     * @return the value of pitaya..product_category.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..product_category.enabled
     *
     * @param enabled the value for pitaya..product_category.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..product_category.create_time
     *
     * @return the value of pitaya..product_category.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..product_category.create_time
     *
     * @param createTime the value for pitaya..product_category.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..product_category.update_time
     *
     * @return the value of pitaya..product_category.update_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..product_category.update_time
     *
     * @param updateTime the value for pitaya..product_category.update_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}