package xyz.nanian.owl.pitaya.entity;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..role.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..role.role_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..role.description
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..role.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..role.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..role.id
     *
     * @return the value of pitaya..role.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..role.id
     *
     * @param id the value for pitaya..role.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..role.role_name
     *
     * @return the value of pitaya..role.role_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..role.role_name
     *
     * @param roleName the value for pitaya..role.role_name
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..role.description
     *
     * @return the value of pitaya..role.description
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..role.description
     *
     * @param description the value for pitaya..role.description
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..role.enabled
     *
     * @return the value of pitaya..role.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..role.enabled
     *
     * @param enabled the value for pitaya..role.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..role.create_time
     *
     * @return the value of pitaya..role.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..role.create_time
     *
     * @param createTime the value for pitaya..role.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}