package xyz.nanian.owl.pitaya.entity;

import java.util.Date;

public class StatsDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..stats_daily.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..stats_daily.stat_date
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date statDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..stats_daily.order_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Integer orderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..stats_daily.new_user_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Integer newUserCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..stats_daily.active_product_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Integer activeProductCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..stats_daily.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..stats_daily.id
     *
     * @return the value of pitaya..stats_daily.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..stats_daily.id
     *
     * @param id the value for pitaya..stats_daily.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..stats_daily.stat_date
     *
     * @return the value of pitaya..stats_daily.stat_date
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getStatDate() {
        return statDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..stats_daily.stat_date
     *
     * @param statDate the value for pitaya..stats_daily.stat_date
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setStatDate(Date statDate) {
        this.statDate = statDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..stats_daily.order_count
     *
     * @return the value of pitaya..stats_daily.order_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Integer getOrderCount() {
        return orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..stats_daily.order_count
     *
     * @param orderCount the value for pitaya..stats_daily.order_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setOrderCount(Integer orderCount) {
        this.orderCount = orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..stats_daily.new_user_count
     *
     * @return the value of pitaya..stats_daily.new_user_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Integer getNewUserCount() {
        return newUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..stats_daily.new_user_count
     *
     * @param newUserCount the value for pitaya..stats_daily.new_user_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setNewUserCount(Integer newUserCount) {
        this.newUserCount = newUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..stats_daily.active_product_count
     *
     * @return the value of pitaya..stats_daily.active_product_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Integer getActiveProductCount() {
        return activeProductCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..stats_daily.active_product_count
     *
     * @param activeProductCount the value for pitaya..stats_daily.active_product_count
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setActiveProductCount(Integer activeProductCount) {
        this.activeProductCount = activeProductCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..stats_daily.create_time
     *
     * @return the value of pitaya..stats_daily.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..stats_daily.create_time
     *
     * @param createTime the value for pitaya..stats_daily.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}