package xyz.nanian.owl.pitaya.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.user_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.username
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.email
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.password
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.remark
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user.last_login
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Date lastLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.id
     *
     * @return the value of pitaya..user.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.id
     *
     * @param id the value for pitaya..user.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.user_code
     *
     * @return the value of pitaya..user.user_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.user_code
     *
     * @param userCode the value for pitaya..user.user_code
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.username
     *
     * @return the value of pitaya..user.username
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.username
     *
     * @param username the value for pitaya..user.username
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.email
     *
     * @return the value of pitaya..user.email
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.email
     *
     * @param email the value for pitaya..user.email
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.password
     *
     * @return the value of pitaya..user.password
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.password
     *
     * @param password the value for pitaya..user.password
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.remark
     *
     * @return the value of pitaya..user.remark
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.remark
     *
     * @param remark the value for pitaya..user.remark
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.enabled
     *
     * @return the value of pitaya..user.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.enabled
     *
     * @param enabled the value for pitaya..user.enabled
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.create_time
     *
     * @return the value of pitaya..user.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.create_time
     *
     * @param createTime the value for pitaya..user.create_time
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user.last_login
     *
     * @return the value of pitaya..user.last_login
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user.last_login
     *
     * @param lastLogin the value for pitaya..user.last_login
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
}