package xyz.nanian.owl.pitaya.entity;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user_role.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user_role.user_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitaya..user_role.role_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user_role.id
     *
     * @return the value of pitaya..user_role.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user_role.id
     *
     * @param id the value for pitaya..user_role.id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user_role.user_id
     *
     * @return the value of pitaya..user_role.user_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user_role.user_id
     *
     * @param userId the value for pitaya..user_role.user_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitaya..user_role.role_id
     *
     * @return the value of pitaya..user_role.role_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitaya..user_role.role_id
     *
     * @param roleId the value for pitaya..user_role.role_id
     *
     * @mbg.generated Sun Nov 09 22:28:26 CST 2025
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}