spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 3436134614@qq.com
    password: msqkbegzfosjdaib    # ${OWL_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp